-- GATE CSE syllabus seed data.
-- Kept separate from 0001_schema.sql so other syllabi can be seeded later
-- without touching table definitions. Safe to re-run: skips if already seeded.
--
-- 11-month plan, 44 weeks, week_number is an absolute index across the whole
-- plan (not reset per month) so weekly goals/streaks can bucket cleanly.

do $$
declare
  v_syllabus_id uuid;
begin
  if exists (select 1 from public.syllabi where name = 'GATE CSE') then
    return;
  end if;

  insert into public.syllabi (name) values ('GATE CSE') returning id into v_syllabus_id;

  insert into public.topics (syllabus_id, subject, title, month, week_number, order_index) values
    -- Month 1: Programming & Data Structures — Part 1
    (v_syllabus_id, 'Programming & Data Structures', 'C Programming: Variables, Data Types, Operators', 1, 1, 1),
    (v_syllabus_id, 'Programming & Data Structures', 'Control Flow: Loops, Conditionals, Switch-Case', 1, 1, 2),
    (v_syllabus_id, 'Programming & Data Structures', 'Functions, Recursion, and Scope', 1, 1, 3),
    (v_syllabus_id, 'Programming & Data Structures', 'Pointers and Dynamic Memory Allocation', 1, 1, 4),
    (v_syllabus_id, 'Programming & Data Structures', 'Arrays and Strings', 1, 2, 5),
    (v_syllabus_id, 'Programming & Data Structures', 'Structures and Unions', 1, 2, 6),
    (v_syllabus_id, 'Algorithms', 'Time and Space Complexity Analysis', 1, 2, 7),
    (v_syllabus_id, 'Algorithms', 'Asymptotic Notations (Big-O, Omega, Theta)', 1, 2, 8),
    (v_syllabus_id, 'Programming & Data Structures', 'Stacks: Array and Linked List Implementation', 1, 3, 9),
    (v_syllabus_id, 'Programming & Data Structures', 'Queues: Array, Linked List, and Circular Queue', 1, 3, 10),
    (v_syllabus_id, 'Programming & Data Structures', 'Linked Lists: Singly, Doubly, Circular', 1, 3, 11),
    (v_syllabus_id, 'Programming & Data Structures', 'Applications of Stacks and Queues', 1, 3, 12),
    (v_syllabus_id, 'Programming & Data Structures', 'Trees: Binary Trees and Traversals', 1, 4, 13),
    (v_syllabus_id, 'Programming & Data Structures', 'Binary Search Trees', 1, 4, 14),
    (v_syllabus_id, 'Programming & Data Structures', 'AVL Trees and Balancing', 1, 4, 15),
    (v_syllabus_id, 'Programming & Data Structures', 'Heaps and Priority Queues', 1, 4, 16),

    -- Month 2: Data Structures — Part 2 + Discrete Mathematics I
    (v_syllabus_id, 'Programming & Data Structures', 'Graphs: Representation (Adjacency Matrix/List)', 2, 5, 17),
    (v_syllabus_id, 'Programming & Data Structures', 'Graph Traversals: BFS and DFS', 2, 5, 18),
    (v_syllabus_id, 'Programming & Data Structures', 'Hashing: Hash Tables and Collision Resolution', 2, 5, 19),
    (v_syllabus_id, 'Programming & Data Structures', 'B-Trees and B+ Trees', 2, 5, 20),
    (v_syllabus_id, 'Discrete Mathematics', 'Set Theory and Relations', 2, 6, 21),
    (v_syllabus_id, 'Discrete Mathematics', 'Functions and Their Properties', 2, 6, 22),
    (v_syllabus_id, 'Discrete Mathematics', 'Propositional Logic', 2, 6, 23),
    (v_syllabus_id, 'Discrete Mathematics', 'Predicate Logic', 2, 6, 24),
    (v_syllabus_id, 'Discrete Mathematics', 'Combinatorics: Permutations and Combinations', 2, 7, 25),
    (v_syllabus_id, 'Discrete Mathematics', 'Principle of Inclusion-Exclusion', 2, 7, 26),
    (v_syllabus_id, 'Discrete Mathematics', 'Recurrence Relations', 2, 7, 27),
    (v_syllabus_id, 'Discrete Mathematics', 'Generating Functions', 2, 7, 28),
    (v_syllabus_id, 'Discrete Mathematics', 'Graph Theory: Basic Properties', 2, 8, 29),
    (v_syllabus_id, 'Discrete Mathematics', 'Group Theory Basics', 2, 8, 30),
    (v_syllabus_id, 'Discrete Mathematics', 'Partial Orders and Lattices', 2, 8, 31),
    (v_syllabus_id, 'Discrete Mathematics', 'Mathematical Induction and Proof Techniques', 2, 8, 32),

    -- Month 3: Algorithms
    (v_syllabus_id, 'Algorithms', 'Divide and Conquer: Merge Sort, Quick Sort', 3, 9, 33),
    (v_syllabus_id, 'Algorithms', 'Sorting Algorithms: Heap Sort, Counting Sort, Radix Sort', 3, 9, 34),
    (v_syllabus_id, 'Algorithms', 'Searching Algorithms: Binary Search and Variants', 3, 9, 35),
    (v_syllabus_id, 'Algorithms', 'Lower Bounds on Sorting', 3, 9, 36),
    (v_syllabus_id, 'Algorithms', 'Greedy Algorithms: Activity Selection, Huffman Coding', 3, 10, 37),
    (v_syllabus_id, 'Algorithms', 'Minimum Spanning Trees: Prim''s and Kruskal''s', 3, 10, 38),
    (v_syllabus_id, 'Algorithms', 'Shortest Path: Dijkstra''s Algorithm', 3, 10, 39),
    (v_syllabus_id, 'Algorithms', 'Shortest Path: Bellman-Ford and Floyd-Warshall', 3, 10, 40),
    (v_syllabus_id, 'Algorithms', 'Dynamic Programming: Fundamentals and Memoization', 3, 11, 41),
    (v_syllabus_id, 'Algorithms', 'DP: Knapsack, LCS, Matrix Chain Multiplication', 3, 11, 42),
    (v_syllabus_id, 'Algorithms', 'Backtracking: N-Queens, Subset Sum', 3, 11, 43),
    (v_syllabus_id, 'Algorithms', 'Amortized Analysis', 3, 11, 44),
    (v_syllabus_id, 'Algorithms', 'NP-Completeness and Reductions', 3, 12, 45),
    (v_syllabus_id, 'Algorithms', 'Approximation Algorithms', 3, 12, 46),
    (v_syllabus_id, 'Algorithms', 'Network Flow: Max-Flow Min-Cut', 3, 12, 47),
    (v_syllabus_id, 'Algorithms', 'Algorithm Design Practice and Problem Solving', 3, 12, 48),

    -- Month 4: Digital Logic + Computer Organization & Architecture
    (v_syllabus_id, 'Digital Logic', 'Number Systems and Codes (Binary, BCD, Gray Code)', 4, 13, 49),
    (v_syllabus_id, 'Digital Logic', 'Boolean Algebra and Logic Gates', 4, 13, 50),
    (v_syllabus_id, 'Digital Logic', 'Combinational Circuits: Adders, Multiplexers, Decoders', 4, 13, 51),
    (v_syllabus_id, 'Digital Logic', 'Karnaugh Maps and Minimization', 4, 13, 52),
    (v_syllabus_id, 'Digital Logic', 'Sequential Circuits: Flip-Flops and Latches', 4, 14, 53),
    (v_syllabus_id, 'Digital Logic', 'Counters and Shift Registers', 4, 14, 54),
    (v_syllabus_id, 'Digital Logic', 'Finite State Machines', 4, 14, 55),
    (v_syllabus_id, 'Digital Logic', 'Memory Elements and Organization', 4, 14, 56),
    (v_syllabus_id, 'Computer Organization & Architecture', 'Machine Instructions and Addressing Modes', 4, 15, 57),
    (v_syllabus_id, 'Computer Organization & Architecture', 'ALU, Data-Path, and Control Unit Design', 4, 15, 58),
    (v_syllabus_id, 'Computer Organization & Architecture', 'Instruction Pipelining and Hazards', 4, 15, 59),
    (v_syllabus_id, 'Computer Organization & Architecture', 'Pipelining: Data, Control, and Structural Hazards', 4, 15, 60),
    (v_syllabus_id, 'Computer Organization & Architecture', 'Memory Hierarchy: Cache Organization and Mapping', 4, 16, 61),
    (v_syllabus_id, 'Computer Organization & Architecture', 'Cache Performance and Replacement Policies', 4, 16, 62),
    (v_syllabus_id, 'Computer Organization & Architecture', 'Main Memory and Virtual Memory Basics', 4, 16, 63),
    (v_syllabus_id, 'Computer Organization & Architecture', 'I/O Interface: Interrupts and DMA', 4, 16, 64),

    -- Month 5: Operating Systems
    (v_syllabus_id, 'Operating Systems', 'OS Fundamentals and System Calls', 5, 17, 65),
    (v_syllabus_id, 'Operating Systems', 'Processes and Process States', 5, 17, 66),
    (v_syllabus_id, 'Operating Systems', 'CPU Scheduling: FCFS, SJF, Priority, Round Robin', 5, 17, 67),
    (v_syllabus_id, 'Operating Systems', 'Multithreading and Concurrency Basics', 5, 17, 68),
    (v_syllabus_id, 'Operating Systems', 'Process Synchronization: Critical Section Problem', 5, 18, 69),
    (v_syllabus_id, 'Operating Systems', 'Semaphores and Mutex Locks', 5, 18, 70),
    (v_syllabus_id, 'Operating Systems', 'Classical Synchronization Problems', 5, 18, 71),
    (v_syllabus_id, 'Operating Systems', 'Deadlocks: Detection, Prevention, and Avoidance', 5, 18, 72),
    (v_syllabus_id, 'Operating Systems', 'Memory Management: Contiguous Allocation', 5, 19, 73),
    (v_syllabus_id, 'Operating Systems', 'Paging and Segmentation', 5, 19, 74),
    (v_syllabus_id, 'Operating Systems', 'Virtual Memory: Demand Paging', 5, 19, 75),
    (v_syllabus_id, 'Operating Systems', 'Page Replacement Algorithms', 5, 19, 76),
    (v_syllabus_id, 'Operating Systems', 'File Systems: Structure and Allocation Methods', 5, 20, 77),
    (v_syllabus_id, 'Operating Systems', 'Disk Scheduling Algorithms', 5, 20, 78),
    (v_syllabus_id, 'Operating Systems', 'I/O Systems and Storage Management', 5, 20, 79),
    (v_syllabus_id, 'Operating Systems', 'OS Case Studies and Practice Problems', 5, 20, 80),

    -- Month 6: Databases (DBMS)
    (v_syllabus_id, 'Databases', 'ER Model and ER Diagrams', 6, 21, 81),
    (v_syllabus_id, 'Databases', 'Relational Model and Relational Algebra', 6, 21, 82),
    (v_syllabus_id, 'Databases', 'SQL: DDL, DML, and Queries', 6, 21, 83),
    (v_syllabus_id, 'Databases', 'SQL: Joins, Subqueries, and Aggregation', 6, 21, 84),
    (v_syllabus_id, 'Databases', 'Functional Dependencies', 6, 22, 85),
    (v_syllabus_id, 'Databases', 'Normalization: 1NF, 2NF, 3NF', 6, 22, 86),
    (v_syllabus_id, 'Databases', 'BCNF and Higher Normal Forms', 6, 22, 87),
    (v_syllabus_id, 'Databases', 'Schema Refinement and Decomposition', 6, 22, 88),
    (v_syllabus_id, 'Databases', 'Transactions and ACID Properties', 6, 23, 89),
    (v_syllabus_id, 'Databases', 'Concurrency Control: Locking Protocols', 6, 23, 90),
    (v_syllabus_id, 'Databases', 'Concurrency Control: Timestamp Ordering', 6, 23, 91),
    (v_syllabus_id, 'Databases', 'Deadlock Handling in Transactions', 6, 23, 92),
    (v_syllabus_id, 'Databases', 'Indexing: B+ Tree Indexes', 6, 24, 93),
    (v_syllabus_id, 'Databases', 'Hashing Techniques in Databases', 6, 24, 94),
    (v_syllabus_id, 'Databases', 'Query Processing and Optimization', 6, 24, 95),
    (v_syllabus_id, 'Databases', 'File Organization and Storage Structures', 6, 24, 96),

    -- Month 7: Computer Networks
    (v_syllabus_id, 'Computer Networks', 'Layered Network Architecture: OSI and TCP/IP', 7, 25, 97),
    (v_syllabus_id, 'Computer Networks', 'Physical Layer Basics', 7, 25, 98),
    (v_syllabus_id, 'Computer Networks', 'Data Link Layer: Framing and Error Detection', 7, 25, 99),
    (v_syllabus_id, 'Computer Networks', 'Flow Control and ARQ Protocols', 7, 25, 100),
    (v_syllabus_id, 'Computer Networks', 'Medium Access Control: CSMA/CD, CSMA/CA', 7, 26, 101),
    (v_syllabus_id, 'Computer Networks', 'LAN Technologies and Switching', 7, 26, 102),
    (v_syllabus_id, 'Computer Networks', 'Network Layer: IP Addressing and Subnetting', 7, 26, 103),
    (v_syllabus_id, 'Computer Networks', 'Routing Algorithms: Distance Vector and Link State', 7, 26, 104),
    (v_syllabus_id, 'Computer Networks', 'IPv4 and IPv6 Fundamentals', 7, 27, 105),
    (v_syllabus_id, 'Computer Networks', 'Transport Layer: UDP and TCP', 7, 27, 106),
    (v_syllabus_id, 'Computer Networks', 'TCP Connection Management and Congestion Control', 7, 27, 107),
    (v_syllabus_id, 'Computer Networks', 'Application Layer Protocols: DNS, HTTP, FTP, SMTP', 7, 27, 108),
    (v_syllabus_id, 'Computer Networks', 'Network Security Basics', 7, 28, 109),
    (v_syllabus_id, 'Computer Networks', 'Firewalls and Network Address Translation', 7, 28, 110),
    (v_syllabus_id, 'Computer Networks', 'Wireless and Mobile Networking Basics', 7, 28, 111),
    (v_syllabus_id, 'Computer Networks', 'Network Practice Problems and Numericals', 7, 28, 112),

    -- Month 8: Theory of Computation
    (v_syllabus_id, 'Theory of Computation', 'Finite Automata: DFA and NFA', 8, 29, 113),
    (v_syllabus_id, 'Theory of Computation', 'Regular Expressions and Regular Languages', 8, 29, 114),
    (v_syllabus_id, 'Theory of Computation', 'Equivalence of DFA, NFA, and Regex', 8, 29, 115),
    (v_syllabus_id, 'Theory of Computation', 'Pumping Lemma for Regular Languages', 8, 29, 116),
    (v_syllabus_id, 'Theory of Computation', 'Context-Free Grammars', 8, 30, 117),
    (v_syllabus_id, 'Theory of Computation', 'Pushdown Automata', 8, 30, 118),
    (v_syllabus_id, 'Theory of Computation', 'Chomsky and Greibach Normal Forms', 8, 30, 119),
    (v_syllabus_id, 'Theory of Computation', 'Pumping Lemma for Context-Free Languages', 8, 30, 120),
    (v_syllabus_id, 'Theory of Computation', 'Turing Machines: Design and Variants', 8, 31, 121),
    (v_syllabus_id, 'Theory of Computation', 'Church-Turing Thesis', 8, 31, 122),
    (v_syllabus_id, 'Theory of Computation', 'Decidability and Undecidability', 8, 31, 123),
    (v_syllabus_id, 'Theory of Computation', 'Recursive and Recursively Enumerable Languages', 8, 31, 124),
    (v_syllabus_id, 'Theory of Computation', 'Rice''s Theorem', 8, 32, 125),
    (v_syllabus_id, 'Theory of Computation', 'Reducibility and NP-Hardness Connection', 8, 32, 126),
    (v_syllabus_id, 'Theory of Computation', 'Chomsky Hierarchy Overview', 8, 32, 127),
    (v_syllabus_id, 'Theory of Computation', 'TOC Practice Problems', 8, 32, 128),

    -- Month 9: Compiler Design + Engineering Mathematics
    (v_syllabus_id, 'Compiler Design', 'Compiler Phases: Lexical Analysis', 9, 33, 129),
    (v_syllabus_id, 'Compiler Design', 'Syntax Analysis: Top-Down Parsing', 9, 33, 130),
    (v_syllabus_id, 'Compiler Design', 'Syntax Analysis: Bottom-Up Parsing (LR Parsers)', 9, 33, 131),
    (v_syllabus_id, 'Compiler Design', 'Syntax-Directed Translation', 9, 33, 132),
    (v_syllabus_id, 'Compiler Design', 'Semantic Analysis and Type Checking', 9, 34, 133),
    (v_syllabus_id, 'Compiler Design', 'Intermediate Code Generation', 9, 34, 134),
    (v_syllabus_id, 'Compiler Design', 'Code Optimization Techniques', 9, 34, 135),
    (v_syllabus_id, 'Compiler Design', 'Runtime Environments and Storage Allocation', 9, 34, 136),
    (v_syllabus_id, 'Engineering Mathematics', 'Linear Algebra: Matrices and Determinants', 9, 35, 137),
    (v_syllabus_id, 'Engineering Mathematics', 'Eigenvalues and Eigenvectors', 9, 35, 138),
    (v_syllabus_id, 'Engineering Mathematics', 'Systems of Linear Equations', 9, 35, 139),
    (v_syllabus_id, 'Engineering Mathematics', 'Vector Spaces Basics', 9, 35, 140),
    (v_syllabus_id, 'Engineering Mathematics', 'Calculus: Limits, Continuity, and Differentiability', 9, 36, 141),
    (v_syllabus_id, 'Engineering Mathematics', 'Maxima, Minima, and Mean Value Theorems', 9, 36, 142),
    (v_syllabus_id, 'Engineering Mathematics', 'Integral Calculus and Applications', 9, 36, 143),
    (v_syllabus_id, 'Engineering Mathematics', 'Probability and Random Variables', 9, 36, 144),

    -- Month 10: General Aptitude + Revision I
    (v_syllabus_id, 'General Aptitude', 'Verbal Ability: Grammar and Sentence Correction', 10, 37, 145),
    (v_syllabus_id, 'General Aptitude', 'Verbal Ability: Reading Comprehension', 10, 37, 146),
    (v_syllabus_id, 'General Aptitude', 'Verbal Ability: Vocabulary and Synonyms/Antonyms', 10, 37, 147),
    (v_syllabus_id, 'General Aptitude', 'Quantitative Aptitude: Number Systems and Arithmetic', 10, 37, 148),
    (v_syllabus_id, 'General Aptitude', 'Quantitative Aptitude: Percentages, Profit and Loss', 10, 38, 149),
    (v_syllabus_id, 'General Aptitude', 'Quantitative Aptitude: Time, Speed, and Distance', 10, 38, 150),
    (v_syllabus_id, 'General Aptitude', 'Quantitative Aptitude: Permutations and Probability', 10, 38, 151),
    (v_syllabus_id, 'General Aptitude', 'Analytical Aptitude: Logical Reasoning', 10, 38, 152),
    (v_syllabus_id, 'General Aptitude', 'Spatial Aptitude and Data Interpretation', 10, 39, 153),
    (v_syllabus_id, 'Revision', 'Revision: Data Structures and Algorithms', 10, 39, 154),
    (v_syllabus_id, 'Revision', 'Revision: Operating Systems and DBMS', 10, 39, 155),
    (v_syllabus_id, 'Revision', 'Revision: Computer Networks and Theory of Computation', 10, 39, 156),
    (v_syllabus_id, 'Revision', 'Revision: Digital Logic and Computer Organization', 10, 40, 157),
    (v_syllabus_id, 'Revision', 'Revision: Compiler Design and Engineering Mathematics', 10, 40, 158),
    (v_syllabus_id, 'Revision', 'Previous Year Question Paper Analysis', 10, 40, 159),
    (v_syllabus_id, 'Revision', 'Formula and Concept Sheet Consolidation', 10, 40, 160),

    -- Month 11: Full Revision + Mock Tests
    (v_syllabus_id, 'Revision', 'Full-Length Mock Test 1 and Analysis', 11, 41, 161),
    (v_syllabus_id, 'Revision', 'Weak Area Identification and Targeted Revision', 11, 41, 162),
    (v_syllabus_id, 'Revision', 'Subject-Wise Speed Practice: Programming & Data Structures', 11, 41, 163),
    (v_syllabus_id, 'Revision', 'Subject-Wise Speed Practice: Algorithms & Theory of Computation', 11, 41, 164),
    (v_syllabus_id, 'Revision', 'Full-Length Mock Test 2 and Analysis', 11, 42, 165),
    (v_syllabus_id, 'Revision', 'Subject-Wise Speed Practice: Operating Systems & Databases', 11, 42, 166),
    (v_syllabus_id, 'Revision', 'Subject-Wise Speed Practice: Computer Networks & Digital Logic', 11, 42, 167),
    (v_syllabus_id, 'Revision', 'Subject-Wise Speed Practice: Computer Organization & Compiler Design', 11, 42, 168),
    (v_syllabus_id, 'Revision', 'Full-Length Mock Test 3 and Analysis', 11, 43, 169),
    (v_syllabus_id, 'Revision', 'Engineering Mathematics and Aptitude Speed Practice', 11, 43, 170),
    (v_syllabus_id, 'Revision', 'Previous 10 Years GATE Papers Practice', 11, 43, 171),
    (v_syllabus_id, 'Revision', 'Time Management and Exam Strategy', 11, 43, 172),
    (v_syllabus_id, 'Revision', 'Full-Length Mock Test 4 and Analysis', 11, 44, 173),
    (v_syllabus_id, 'Revision', 'Final Revision: Formula Sheets and Short Notes', 11, 44, 174),
    (v_syllabus_id, 'Revision', 'Rest, Recovery, and Exam-Day Logistics Planning', 11, 44, 175),
    (v_syllabus_id, 'Revision', 'Final Mock Test and Self-Assessment', 11, 44, 176);
end $$;
